import {
  BROWN_1,
  BROWN_2,
  BROWN_3,
  DIRT_WET,
  DIRT_NORMAL,
  DIRT_DRY,
  AIR_WET,
  AIR_DRY,
  PLANT_DYING,
  PLANT_GREEN,
  PLANT_1,
  PLANT_2,
  PLANT_3,
  PLANT_4,
  PLANT_5,
} from './colors';

const STEP = 10;

const SHRINK_FACTOR = 1;

const WINDOW_WIDTH = window.innerWidth;
const WINDOW_HEIGHT = window.innerHeight;

const DISPLAY_SIZE_X = Math.ceil((WINDOW_WIDTH / STEP) * SHRINK_FACTOR);
const DISPLAY_SIZE_Y = Math.ceil((WINDOW_HEIGHT / STEP) * SHRINK_FACTOR);

const LAYER_COUNT = 3;

const BLOCKS_PROCESSED_PER_STEP = 1000;
const RAIN_PER_STEP = 1;

const PROBABILITY_DECOMPOSE = 0.001;

const MIN_MOISTURE = 0;
const MIN_NUTRIENTS = 0;

const DRAW_PER_STEP_MOISTURE_PLANT = 5;
const DRAW_PER_STEP_NUTRIENTS_PLANT = 5;
const HEALTH_DROP_PER_STEP_PLANT = 10;
const HEALTH_REGAIN_PER_STEP_PLANT = 10;
const THRESHOLD_TO_LOSE_HEALTH_PLANT = 10;
const HEALTH_DROP_MOISTURE_THRESHOLD_PLANT = 10;
const HEALTH_DROP_NUTRIENTS_THRESHOLD_PLANT = 10;
const GROWTH_MAX_PLANT = 100;
const GROWTH_MOISTURE_THRESHOLD_PLANT = 50;
const GROWTH_NUTRIENTS_THESHOLD_PLANT = 50;
const GROWTH_PER_STEP_PLANT = 1;
const GROWTH_COST_MOISTURE_PLANT = 5;
const GROWTH_COST_NUTRIENTS_PLANT = 5;
const HEALTH_COST_MOISTURE_PLANT = 10;
const HEALTH_COST_NUTRIENTS_PLANT = 10;
const SUSTAIN_COST_MOISTURE_PLANT = 1;
const SUSTAIN_COST_NUTRIENTS_PLANT = 1;

const colors = {
  BROWN_1,
  BROWN_2,
  BROWN_3,
  DIRT_WET,
  DIRT_NORMAL,
  DIRT_DRY,
  AIR_WET,
  AIR_DRY,
  PLANT_DYING,
  PLANT_GREEN,
  PLANT_1,
  PLANT_2,
  PLANT_3,
  PLANT_4,
  PLANT_5,
};

export {
  STEP,
  SHRINK_FACTOR,
  WINDOW_WIDTH,
  WINDOW_HEIGHT,
  DISPLAY_SIZE_X,
  DISPLAY_SIZE_Y,
  LAYER_COUNT,
  MIN_MOISTURE,
  MIN_NUTRIENTS,
  BLOCKS_PROCESSED_PER_STEP,
  RAIN_PER_STEP,
  PROBABILITY_DECOMPOSE,
  DRAW_PER_STEP_MOISTURE_PLANT,
  DRAW_PER_STEP_NUTRIENTS_PLANT,
  HEALTH_DROP_PER_STEP_PLANT,
  HEALTH_REGAIN_PER_STEP_PLANT,
  THRESHOLD_TO_LOSE_HEALTH_PLANT,
  HEALTH_DROP_MOISTURE_THRESHOLD_PLANT,
  HEALTH_DROP_NUTRIENTS_THRESHOLD_PLANT,
  GROWTH_MAX_PLANT,
  GROWTH_MOISTURE_THRESHOLD_PLANT,
  GROWTH_NUTRIENTS_THESHOLD_PLANT,
  GROWTH_PER_STEP_PLANT,
  GROWTH_COST_MOISTURE_PLANT,
  GROWTH_COST_NUTRIENTS_PLANT,
  HEALTH_COST_MOISTURE_PLANT,
  HEALTH_COST_NUTRIENTS_PLANT,
  SUSTAIN_COST_MOISTURE_PLANT,
  SUSTAIN_COST_NUTRIENTS_PLANT,
  colors,
};
